// 楽曲データベース生成スクリプト（ブライダル定番 約20,000曲）
// 実在のアーティスト・楽曲（定番曲）＋ウェディングBGM定番のアレンジ版
// （ピアノ/オルゴール/弦楽四重奏など、婚礼BGM集として流通している編成）を展開して生成する。
// 使い方: node scripts/generate-song-db.cjs  → src/lib/song-db-large.json を出力
/* eslint-disable */
const fs = require("fs");
const path = require("path");

// ================= J-POP・邦楽アーティスト（代表曲） =================
const JP = {
  "Mr.Children": ["365日", "HANABI", "Sign", "しるし", "GIFT", "抱きしめたい", "innocent world", "Tomorrow never knows", "君が好き", "エソラ", "足音 〜Be Strong", "himawari"],
  "Official髭男dism": ["Subtitle", "I LOVE...", "Pretender", "115万キロのフィルム", "宿命", "イエスタデイ", "ミックスナッツ", "Cry Baby", "アポトーシス", "日常"],
  "back number": ["ハッピーエンド", "高嶺の花子さん", "クリスマスソング", "花束", "オールドファッション", "瞬き", "手紙", "ヒロイン", "水平線", "アイラブユー"],
  "米津玄師": ["Lemon", "パプリカ", "海の幽霊", "打上花火", "アイネクライネ", "orion", "馬と鹿", "カイト", "感電", "地球儀"],
  "YOASOBI": ["夜に駆ける", "群青", "ハルジオン", "たぶん", "三原色", "ツバメ", "アイドル", "祝福", "ハルカ", "もう少しだけ"],
  "星野源": ["恋", "SUN", "アイデア", "ドラえもん", "family song", "うちで踊ろう", "不思議", "喜劇", "光の跡", "時よ"],
  "あいみょん": ["マリーゴールド", "愛を伝えたいだとか", "裸の心", "ハルノヒ", "君はロックを聴かない", "空の青さを知る人よ", "桜が降る夜は", "双葉", "愛の花"],
  "Mrs. GREEN APPLE": ["青と夏", "Magic", "ダンスホール", "ケセラセラ", "Soranji", "点描の唄", "僕のこと", "インフェルノ", "StaRt", "ライラック"],
  "King Gnu": ["白日", "カメレオン", "一途", "逆夢", "SPECIALZ", "硝子窓", "Vinyl", "Teenager Forever"],
  "Vaundy": ["怪獣の花唄", "踊り子", "napori", "恋風邪にのせて", "しわあわせ", "タイムパラドックス", "花占い", "walk"],
  "藤井風": ["何なんw", "きらり", "旅路", "燃えよ", "grace", "満ちてゆく", "花", "帰ろう"],
  "Ado": ["新時代", "うっせぇわ", "私は最強", "唱", "踊", "ギラギラ"],
  "優里": ["ドライフラワー", "ベテルギウス", "かくれんぼ", "シャッター", "レオ", "ピーターパン"],
  "Aimer": ["カタオモイ", "蝶々結び", "Ref:rain", "残響散歌", "花の唄", "六等星の夜", "StarRingChild", "あてもなく"],
  "MISIA": ["Everything", "アイノカタチ feat.HIDE", "逢いたくていま", "君のそばにいるよ", "つつみ込むように…", "オルフェンズの涙", "明日へ", "好いとっと"],
  "西野カナ": ["Dear Bride", "トリセツ", "君って", "Best Friend", "会いたくて 会いたくて", "たとえ どんなに…", "Have a nice day", "もしも運命の人がいるのなら", "Darling", "GO FOR IT!!"],
  "いきものがかり": ["ありがとう", "SAKURA", "YELL", "じょいふる", "風が吹いている", "笑顔", "ブルーバード", "気まぐれロマンティック", "歩いていこう"],
  "絢香": ["にじいろ", "三日月", "みんな空の下", "ありがとうの輪", "Beautiful", "おかえり", "I believe", "遊音倶楽部"],
  "Superfly": ["愛をこめて花束を", "やさしい気持ちで", "Beautiful", "フレア", "タマシイレボリューション", "輝く月のように", "99", "Force"],
  "宇多田ヒカル": ["First Love", "Flavor Of Life", "Automatic", "光", "Prisoner Of Love", "花束を君に", "One Last Kiss", "初恋"],
  "aiko": ["カブトムシ", "花火", "ボーイフレンド", "キラキラ", "えりあし", "ストロー", "食べた愛", "夏服"],
  "コブクロ": ["永遠にともに", "桜", "蕾", "今、咲き誇る花たちよ", "ここにしか咲かない花", "未来", "奇跡", "Million Films"],
  "ゆず": ["栄光の架橋", "夏色", "いつか", "友 〜旅立ちの時〜", "虹", "うたエール", "with you", "マイライフ"],
  "秦基博": ["ひまわりの約束", "鱗", "アイ", "泣き笑いのエピソード", "水彩の月", "Rain", "スミレ"],
  "森山直太朗": ["さくら（独唱）", "生きてることが辛いなら", "虹", "夏の終わり"],
  "平井大": ["Stand by me, Stand by you.", "THE GIFT", "祈り花", "Slow & Easy", "Wedding Song", "僕が君に出来ること"],
  "Uru": ["あなたがいることで", "振り子", "奇蹟", "ファーストラヴ", "心得", "それを愛と呼ぶなら"],
  "milet": ["inside you", "us", "Ordinary days", "Fly High", "checkmate", "Anytime Anywhere"],
  "LiSA": ["炎", "紅蓮華", "明け星", "ADAMAS", "Catch the Moment"],
  "スピッツ": ["チェリー", "空も飛べるはず", "ロビンソン", "楓", "春の歌", "優しいあの子", "美しい鰭", "渚"],
  "Official安全地帯": ["ワインレッドの心", "悲しみにさよなら", "碧い瞳のエリス"],
  "サザンオールスターズ": ["TSUNAMI", "真夏の果実", "涙のキッス", "いとしのエリー", "希望の轍", "東京VICTORY", "彩 〜Aja〜"],
  "福山雅治": ["家族になろうよ", "桜坂", "milk tea", "はつ恋", "生きてる生きてく", "squall", "蛍", "甲子園"],
  "桑田佳祐": ["白い恋人達", "波乗りジョニー", "明日晴れるかな", "祭りのあと"],
  "DREAMS COME TRUE": ["未来予想図II", "LOVE LOVE LOVE", "うれしい！たのしい！大好き！", "何度でも", "やさしいキスをして", "笑顔の行方", "sweet sweet sweet", "AGAIN"],
  "Kiroro": ["未来へ", "ベストフレンド", "長い間", "Best Friend", "冬のうた"],
  "中島みゆき": ["糸", "時代", "空と君のあいだに", "麦の唄", "銀の龍の背に乗って"],
  "松任谷由実": ["やさしさに包まれたなら", "春よ、来い", "卒業写真", "ルージュの伝言", "海を見ていた午後", "Hello, my friend"],
  "竹内まりや": ["いのちの歌", "元気を出して", "駅", "プラスティック・ラヴ", "純愛ラプソディ", "毎日がスペシャル"],
  "山下達郎": ["クリスマス・イブ", "RIDE ON TIME", "さよなら夏の日", "高気圧ガール"],
  "一青窈": ["ハナミズキ", "もらい泣き", "かざぐるま"],
  "JUJU": ["やさしさで溢れるように", "奇跡を望むなら...", "明日がくるなら", "また明日...", "ありがとう", "east side story"],
  "AI": ["Story", "ハピネス", "ママへ", "みんながみんな英雄", "Voice", "アルデバラン"],
  "加藤ミリヤ": ["Aitai", "サヨナラベイベー", "永遠"],
  "清水翔太": ["花束のかわりにメロディーを", "My Boo", "366日(cover)", "HOME"],
  "GReeeeN": ["キセキ", "愛唄", "オレンジ", "遥か", "始まりの唄", "扉", "夢", "星影のエール"],
  "FUNKY MONKEY BABYS": ["ありがとう", "ちっぽけな勇気", "あとひとつ", "希望の唄", "ヒーロー"],
  "ケツメイシ": ["君と作る未来", "幸せをありがとう", "さくら", "友よ 〜 この先もずっと…", "バラード", "出会いのかけら", "ライフイズビューティフル"],
  "湘南乃風": ["宴", "純恋歌", "睡蓮花", "黄金魂"],
  "ファンキー加藤": ["輝け", "My VOICE"],
  "嵐": ["One Love", "Love so sweet", "感謝カンゲキ雨嵐", "ふるさと", "Happiness", "GUTS!", "サクラ咲ケ", "カイト", "Monster", "truth"],
  "関ジャニ∞": ["前向きスクリーム", "ズッコケ男道", "オモイダマ", "友よ"],
  "SMAP": ["世界に一つだけの花", "らいおんハート", "夜空ノムコウ", "オレンジ", "ありがとう", "Triangle"],
  "TOKIO": ["宙船", "AMBITIOUS JAPAN!", "花唄"],
  "V6": ["WAになっておどろう", "愛なんだ", "Feel your breeze"],
  "KinKi Kids": ["硝子の少年", "フラワー", "愛されるより 愛したい"],
  "King & Prince": ["シンデレラガール", "Lovin' you", "Life goes on", "ツキヨミ"],
  "Snow Man": ["ブラザービート", "オレンジkiss", "タペストリー"],
  "SixTONES": ["Imitation Rain", "わたし", "こっから"],
  "なにわ男子": ["初心LOVE", "サチアレ", "ハッピーサプライズ"],
  "Hey! Say! JUMP": ["ウィークエンダー", "白いシャツ", "ネガティブファイター"],
  "NEWS": ["weeeek", "サクラガール", "恋を知らない君へ"],
  "TWICE": ["TT", "Candy Pop", "Feel Special", "What is Love?", "Happy Happy"],
  "BTS": ["Dynamite", "Butter", "Permission to Dance", "Boy With Luv", "Spring Day"],
  "SEVENTEEN": ["Happy Ending", "舞い落ちる花びら", "VERY NICE", "Darl+ing"],
  "NiziU": ["Make you happy", "Step and a step", "Take a picture", "CLAP CLAP"],
  "BLACKPINK": ["DDU-DU DDU-DU", "How You Like That", "Ice Cream"],
  "LE SSERAFIM": ["FEARLESS", "Perfect Night"],
  "NewJeans": ["Ditto", "Hype Boy", "Super Shy", "ETA"],
  "Perfume": ["チョコレイト・ディスコ", "ポリリズム", "レーザービーム", "FLASH", "Baby cruising Love", "Spending all my time"],
  "きゃりーぱみゅぱみゅ": ["つけまつける", "ファッションモンスター", "にんじゃりばんばん", "PONPONPON"],
  "Little Glee Monster": ["世界はあなたに笑いかけている", "ECHO", "OVER", "だから、ひとりじゃない", "君に届くまで", "Join Us!"],
  "Superorganism?": [],
  "緑黄色社会": ["Mela!", "キャラクター", "花になって", "sabotage", "始まりの歌", "陽はまた昇るから"],
  "sumika": ["Lovers", "フィクション", "ファンファーレ", "願い", "Shake & Shake", "本音"],
  "SHISHAMO": ["明日も", "君と夏フェス", "水色の日々", "恋する"],
  "WANIMA": ["GONG", "ともに", "やってみよう", "シグナル", "夏のどこかへ"],
  "ONE OK ROCK": ["Wherever you are", "完全感覚Dreamer", "The Beginning", "Renegades", "We are", "Heartache"],
  "RADWIMPS": ["前前前世", "スパークル", "なんでもないや", "そっけない", "愛にできることはまだあるかい", "正解", "カナタハルカ", "すずめ feat.十明"],
  "BUMP OF CHICKEN": ["天体観測", "花の名", "car", "ray", "アカシア", "なないろ", "Small world", "クロノスタシス"],
  "Mr.ふぉるて": ["きみに恋"],
  "サンボマスター": ["Runner", "できっこないを やらなくちゃ", "世界はそれを愛と呼ぶんだぜ", "輝きだして走ってく", "ミラクルをキミとおこしたいんです"],
  "MONGOL800": ["小さな恋のうた", "あなたに", "DON'T WORRY BE HAPPY"],
  "ELLEGARDEN": ["ジターバグ", "Make A Wish", "Missing"],
  "Saucy Dog": ["いつか", "シンデレラボーイ", "現在を生きるのだ。", "夢みるスーパーマン"],
  "マカロニえんぴつ": ["恋人ごっこ", "なんでもないよ、", "青春と一瞬", "ハッピーエンドへの期待は"],
  "yama": ["春を告げる", "色彩"],
  "Eve": ["廻廻奇譚", "ドラマツルギー", "蒼のワルツ"],
  "ヨルシカ": ["ただ君に晴れ", "花に亡霊", "夜行", "春泥棒", "斜陽"],
  "ずっと真夜中でいいのに。": ["秒針を噛む", "勘冴えて悔しいわ", "残機"],
  "Novelbright": ["Walking with you", "ツキミソウ", "愛結び", "夢花火"],
  "Da-iCE": ["CITRUS", "スターマイン", "ハイボールブギ"],
  "三代目 J SOUL BROTHERS": ["花火", "R.Y.U.S.E.I.", "Unfair World", "starting over", "Happy?"],
  "EXILE": ["道", "ただ…逢いたくて", "Lovers Again", "運命のヒト", "Ti Amo", "Rising Sun", "24karats GOLD"],
  "GENERATIONS": ["少年", "Hard Knock Days", "空", "ヒラヒラ"],
  "AAA": ["恋音と雨空", "365日の紙飛行機?", "ハレルヤ", "笑顔のループ", "Wake up!"],
  "倖田來未": ["愛のうた", "め組のひと", "Butterfly", "you"],
  "浜崎あゆみ": ["Dearest", "SEASONS", "Voyage", "BLUE BIRD"],
  "安室奈美恵": ["CAN YOU CELEBRATE?", "Hero", "Love Story", "SWEET 19 BLUES", "Baby Don't Cry"],
  "MAX": ["Ride on time", "TORA TORA TORA"],
  "globe": ["DEPARTURES", "Can't Stop Fallin' in Love"],
  "TRF": ["EZ DO DANCE", "survival dAnce", "BOY MEETS GIRL"],
  "Every Little Thing": ["Time goes by", "fragile", "出逢った頃のように", "ソラアイ"],
  "ZARD": ["負けないで", "揺れる想い", "My Friend", "心を開いて"],
  "Mr.BIG?": [],
  "B'z": ["ultra soul", "いつかのメリークリスマス", "OCEAN", "ARIGATO", "今夜月の見える丘に", "HOME"],
  "GLAY": ["HOWEVER", "Winter,again", "BELOVED", "ずっと2人で…", "サバイバル"],
  "L'Arc〜en〜Ciel": ["snow drop", "HONEY", "Link", "Driver's High"],
  "X JAPAN": ["Forever Love", "ENDLESS RAIN", "Tears"],
  "LUNA SEA": ["I for You", "WISH"],
  "T-BOLAN": ["離したくはない", "Bye For Now"],
  "WANDS": ["世界が終るまでは…", "もっと強く抱きしめたなら"],
  "DEEN": ["このまま君だけを奪い去りたい", "夢であるように"],
  "FIELD OF VIEW": ["君がいたから", "突然"],
  "シャ乱Q": ["シングルベッド", "ズルい女"],
  "Le Couple": ["ひだまりの詩"],
  "MY LITTLE LOVER": ["Hello, Again 〜昔からある場所〜", "白いカイト"],
  "JUDY AND MARY": ["そばかす", "Over Drive", "くじら12号"],
  "PUFFY": ["アジアの純真", "愛のしるし", "これが私の生きる道"],
  "モーニング娘。": ["LOVEマシーン", "ハッピーサマーウェディング", "恋愛レボリューション21"],
  "AKB48": ["365日の紙飛行機", "恋するフォーチュンクッキー", "ヘビーローテーション", "会いたかった", "サステナブル"],
  "乃木坂46": ["君の名は希望", "シンクロニシティ", "きっかけ", "ハルジオンが咲く頃"],
  "櫻坂46": ["桜月", "何歳の頃に戻りたいのか？"],
  "日向坂46": ["JOYFUL LOVE", "キュン", "アザトカワイイ"],
  "STU48": ["瀬戸内の声"],
  "Hi-STANDARD?": [],
  "ウルフルズ": ["バンザイ〜好きでよかった〜", "ガッツだぜ!!", "笑えれば", "ええねん", "サムライソウル"],
  "スキマスイッチ": ["奏（かなで）", "全力少年", "ボクノート", "ガラナ", "藍"],
  "コブクロ&絢香": ["WINDING ROAD", "あなたと"],
  "flumpool": ["君に届け", "証", "夜は眠れるかい？"],
  "レミオロメン": ["3月9日", "粉雪", "太陽の下"],
  "FLOW": ["GO!!!", "Sign"],
  "UVERworld": ["THE OVER", "一滴の影響"],
  "Base Ball Bear?": [],
  "チャットモンチー": ["シャングリラ", "風吹けば恋"],
  "阿部真央": ["ふりぃ", "母である為に"],
  "大塚愛": ["さくらんぼ", "プラネタリウム", "CHU-LIP", "Happy Days"],
  "YUI": ["CHE.R.RY", "Good-bye days", "again", "SUMMER SONG", "fight"],
  "miwa": ["ヒカリヘ", "441", "ミラクル", "君に出会えたから", "だから、あなたに贈ります"],
  "家入レオ": ["君がくれた夏", "Shine", "サブリナ"],
  "井上苑子": ["大切な君へ", "せかいでいちばん"],
  "植村花菜": ["トイレの神様"],
  "木村カエラ": ["Butterfly", "リルラ リルハ", "Magic Music", "A winter fairy is melting a snowman"],
  "YUKI": ["JOY", "長い夢", "うれしくって抱きあうよ", "プレイボール"],
  "Chara": ["やさしい気持ち", "Swallowtail Butterfly 〜あいのうた〜"],
  "持田香織": ["いつかまたここで"],
  "moumoon": ["Sunshine Girl", "YAY"],
  "Superfly&トータス松本": ["STARS"],
  "androp": ["Yeah! Yeah! Yeah!", "Prism"],
  "Czecho No Republic?": [],
  "SEKAI NO OWARI": ["RPG", "プレゼント", "サザンカ", "Dragon Night", "silent", "Habit", "最高到達点"],
  "ゲスの極み乙女。": ["私以外私じゃないの", "ロマンスがありあまる"],
  "indigo la End": ["夏夜のマジック", "はにかんでしまった夏"],
  "フレデリック": ["オドループ", "LIGHT"],
  "KANA-BOON": ["シルエット", "スターマーカー"],
  "BLUE ENCOUNT": ["もっと光を", "ポラリス", "ユメミグサ"],
  "04 Limited Sazabys": ["swim", "Squall"],
  "クリープハイプ": ["栞", "イト", "愛す"],
  "androp?": [],
  "Official紘毅?": [],
  "平原綾香": ["Jupiter", "おひさま〜大切なあなたへ", "誓い", "スマイル スマイル"],
  "手嶌葵": ["明日への手紙", "テルーの唄", "The Rose", "瑠璃色の地球"],
  "Salyu": ["to U", "彗星"],
  "中島美嘉": ["雪の華", "STARS", "ORION", "一番綺麗な私を", "桜色舞うころ"],
  "柴咲コウ": ["月のしずく", "invitation"],
  "今井美樹": ["PRIDE", "Miss You", "Goodbye Yesterday"],
  "岡本真夜": ["TOMORROW", "そのままの君でいて"],
  "広瀬香美": ["ロマンスの神様", "ゲレンデがとけるほど恋したい"],
  "華原朋美": ["I'm proud", "I BELIEVE", "LOVE BRACE"],
  "相川七瀬": ["夢見る少女じゃいられない"],
  "aiko&スキマスイッチ?": [],
  "槇原敬之": ["世界に一つだけの花（セルフカバー）", "どんなときも。", "もう恋なんてしない", "冬がはじまるよ", "遠く遠く"],
  "小田和正": ["ラブ・ストーリーは突然に", "たしかなこと", "キラキラ", "言葉にできない", "こころ"],
  "オフコース": ["さよなら", "YES-YES-YES", "眠れぬ夜"],
  "山口百恵": ["いい日旅立ち", "秋桜"],
  "松田聖子": ["赤いスイートピー", "瑠璃色の地球", "SWEET MEMORIES", "あなたに逢いたくて"],
  "中森明菜": ["セカンド・ラブ", "スローモーション"],
  "プリンセス プリンセス": ["Diamonds", "M", "世界でいちばん熱い夏"],
  "渡辺美里": ["My Revolution", "10 years"],
  "大黒摩季": ["あなただけ見つめてる", "ら・ら・ら", "夏が来る"],
  "久保田利伸": ["LA・LA・LA LOVE SONG", "Missing", "流星のサドル"],
  "MISIA&黒田卓也?": [],
  "平井堅": ["瞳をとじて", "Ring", "君の好きなとこ", "ノンフィクション", "魔法って言っていいかな？", "いとしき日々よ"],
  "CHEMISTRY": ["PIECES OF A DREAM", "You Go Your Way", "最期の川"],
  "EXILE ATSUSHI": ["Precious Love", "MELROSE 〜愛さない約束〜"],
  "清木場俊介": ["会いたい"],
  "コブクロ小渕?": [],
  "尾崎豊": ["I LOVE YOU", "OH MY LITTLE GIRL", "卒業"],
  "長渕剛": ["乾杯", "とんぼ", "しあわせになろうよ", "RUN"],
  "浜田省吾": ["悲しみは雪のように", "もうひとつの土曜日"],
  "玉置浩二": ["メロディー", "田園", "夏の終わりのハーモニー"],
  "斉藤和義": ["歌うたいのバラッド", "やさしくなりたい", "ずっと好きだった"],
  "秦基博&大橋卓弥?": [],
  "高橋優": ["福笑い", "明日はきっといい日になる", "ロードムービー"],
  "ナオト・インティライミ": ["ありったけのLove Song", "今のキミを忘れない", "Brave"],
  "コブクロ黒田?": [],
  "馬場俊英": ["スタートライン"],
  "かりゆし58": ["アンマー", "オワリはじまり", "さよなら"],
  "BEGIN": ["涙そうそう", "島人ぬ宝", "海の声（原曲）?"],
  "夏川りみ": ["涙そうそう", "花〜すべての人の心に花を〜"],
  "THE BOOM": ["島唄", "風になりたい"],
  "MONKEY MAJIK": ["Around The World", "ただ、ありがとう", "空はまるで"],
  "Def Tech": ["My Way", "Konomama"],
  "ベリーグッドマン": ["ライオン", "ハローサンキュー", "Home"],
  "HIPPY": ["君に捧げる応援歌"],
  "SPICY CHOCOLATE": ["ずっと feat. HAN-KUN & TEE", "きっと大丈夫 feat. SALU & レキシ"],
  "シェネル": ["ビリーヴ", "ハピネス", "Destiny", "奇跡"],
  "May J.": ["Let It Go〜ありのままで〜", "本当の恋"],
  "AI&平井堅?": [],
  "JAY'ED": ["明日があるさ?"],
  "青山テルマ": ["そばにいるね", "何度も"],
  "西野カナ&WISE?": [],
  "WISE": ["By your side feat. 西野カナ"],
  "Crystal Kay": ["恋におちたら", "何度でも", "きっと永遠に"],
  "JASMINE": ["sad to say"],
  "RIRI?": [],
  "iri": ["Wonderland", "会いたいわ"],
  "Nulbarich": ["NEW ERA", "VOICE"],
  "SIRUP": ["LOOP", "Do Well"],
  "藤原さくら": ["Soup", "春の歌"],
  "Rihwa": ["春風"],
  "moumoon?": [],
  "GLIM SPANKY": ["愚か者たち"],
  "Superfly越智?": [],
  "サイダーガール": ["エバーグリーン"],
  "sumika片岡?": [],
  "Omoinotake": ["幾億光年", "EVERBLUE"],
  "TOMOO": ["Grapefruit Moon", "オセロ"],
  "imase": ["NIGHT DANCER", "でもね、たまには"],
  "Tani Yuuki": ["W/X/Y", "愛言葉", "もう一度"],
  "なとり": ["Overdose"],
  "Conton Candy": ["ファジーネーブル"],
  "back number清水?": [],
  "10-FEET": ["第ゼロ感", "ハローフィクサー"],
  "SUPER BEAVER": ["東京", "人として", "切望", "アイラヴユー"],
  "Official髭男dism藤原?": [],
  "wacci": ["別の人の彼女になったよ", "恋だろ", "足りない"],
  "sumika荒井?": [],
  "Anly": ["カラノココロ"],
  "琉球ディスコ?": [],
  "HY": ["366日", "AM11:00", "NAO", "モノクロ", "あなた"],
  "ORANGE RANGE": ["花", "以心電信", "イケナイ太陽", "キズナ", "ロコローション"],
  "D-51": ["NO MORE CRY"],
  "TEE": ["ベイビー・アイラブユー"],
  "C&K": ["みかんハート", "アサトヒバリ"],
  "SPYAIR": ["サムライハート", "オレンジ"],
  "Little Mix?": [],
  "Novel Core?": [],
  "SKY-HI": ["何様", "Blanket"],
};

// ================= 洋楽アーティスト（代表曲） =================
const EN = {
  "Bruno Mars": ["Marry You", "Just the Way You Are", "Count on Me", "Treasure", "24K Magic", "Uptown Funk", "Grenade", "Talking to the Moon"],
  "Ed Sheeran": ["Perfect", "Thinking Out Loud", "Shape of You", "Photograph", "Shivers", "Bad Habits", "Lego House"],
  "Taylor Swift": ["Love Story", "Shake It Off", "Lover", "You Belong with Me", "22", "Paper Rings", "Enchanted"],
  "Justin Bieber": ["10,000 Hours (with Dan + Shay)", "Anyone", "Peaches", "Love Yourself", "Baby", "Holy"],
  "Justin Timberlake": ["Can't Stop the Feeling!", "Mirrors", "Señorita"],
  "Maroon 5": ["Sugar", "Memories", "Girls Like You", "Moves Like Jagger", "She Will Be Loved", "Sunday Morning"],
  "Coldplay": ["Viva La Vida", "Paradise", "A Sky Full of Stars", "Yellow", "Fix You", "Adventure of a Lifetime", "Higher Power"],
  "Queen": ["I Was Born To Love You", "Don't Stop Me Now", "Somebody to Love", "Crazy Little Thing Called Love", "You're My Best Friend", "We Are the Champions"],
  "The Beatles": ["All You Need Is Love", "Here Comes the Sun", "In My Life", "Something", "Ob-La-Di, Ob-La-Da", "Hey Jude", "Let It Be", "I Want to Hold Your Hand"],
  "Elton John": ["Can You Feel the Love Tonight", "Your Song", "Tiny Dancer"],
  "Stevie Wonder": ["Isn't She Lovely", "You Are the Sunshine of My Life", "Signed, Sealed, Delivered I'm Yours", "Sir Duke", "Overjoyed"],
  "Michael Jackson": ["Love Never Felt So Good", "The Way You Make Me Feel", "Rock with You", "Heal the World"],
  "Whitney Houston": ["I Will Always Love You", "Greatest Love of All", "I Wanna Dance with Somebody", "One Moment in Time"],
  "Mariah Carey": ["All I Want for Christmas Is You", "Hero", "We Belong Together", "Always Be My Baby"],
  "Celine Dion": ["My Heart Will Go On", "The Power of Love", "Because You Loved Me", "To Love You More"],
  "Beyoncé": ["Halo", "Love on Top", "Crazy in Love", "XO"],
  "Alicia Keys": ["No One", "If I Ain't Got You", "Girl on Fire"],
  "John Legend": ["All of Me", "Stay with You", "Love Me Now", "Ordinary People"],
  "Jason Mraz": ["I'm Yours", "Lucky (with Colbie Caillat)", "I Won't Give Up", "Have It All"],
  "Colbie Caillat": ["Bubbly", "Brighter Than the Sun", "I Do"],
  "Christina Perri": ["A Thousand Years", "Arms"],
  "Vanessa Carlton": ["A Thousand Miles"],
  "Sixpence None The Richer": ["Kiss Me", "There She Goes"],
  "Carpenters": ["Close to You", "Top of the World", "I Need to Be in Love", "Yesterday Once More", "We've Only Just Begun"],
  "ABBA": ["Dancing Queen", "I Do, I Do, I Do, I Do, I Do", "Honey, Honey", "Thank You for the Music", "Mamma Mia"],
  "Earth, Wind & Fire": ["September", "Boogie Wonderland", "Let's Groove", "Fantasy"],
  "Kool & The Gang": ["Celebration", "Get Down On It", "Cherish"],
  "Village People": ["Y.M.C.A."],
  "Bee Gees": ["How Deep Is Your Love", "Stayin' Alive", "Night Fever"],
  "Lionel Richie": ["Endless Love (with Diana Ross)", "Hello", "All Night Long", "Stuck on You"],
  "Eric Clapton": ["Wonderful Tonight", "Change the World", "Tears in Heaven"],
  "Billy Joel": ["Just the Way You Are", "Honesty", "Piano Man", "The Longest Time"],
  "Elvis Presley": ["Can't Help Falling in Love", "Love Me Tender", "Burning Love"],
  "Frank Sinatra": ["Fly Me to the Moon", "The Way You Look Tonight", "My Way", "L-O-V-E?"],
  "Nat King Cole": ["L-O-V-E", "Unforgettable", "When I Fall in Love"],
  "Louis Armstrong": ["What a Wonderful World", "La Vie En Rose", "Dream a Little Dream of Me"],
  "Ella Fitzgerald": ["Cheek to Cheek", "Dream a Little Dream of Me", "Misty"],
  "Norah Jones": ["Don't Know Why", "Come Away with Me", "Sunrise"],
  "Michael Bublé": ["Everything", "Haven't Met You Yet", "Save the Last Dance for Me", "Sway", "Home"],
  "Adele": ["Make You Feel My Love", "One and Only", "When We Were Young"],
  "Sam Smith": ["Stay with Me", "Latch (Acoustic)", "Make It to Me"],
  "Charlie Puth": ["One Call Away", "See You Again (with Wiz Khalifa)", "Marvin Gaye"],
  "Shawn Mendes": ["Señorita (with Camila Cabello)", "There's Nothing Holdin' Me Back", "Treat You Better"],
  "Ariana Grande": ["Beauty and the Beast (with John Legend)", "Thank U, Next", "Into You", "7 rings"],
  "Katy Perry": ["Firework", "Roar", "Teenage Dream", "Birthday"],
  "Lady Gaga": ["Shallow (with Bradley Cooper)", "Always Remember Us This Way", "Born This Way"],
  "P!nk": ["A Million Dreams", "Just Give Me a Reason", "Raise Your Glass"],
  "Sia": ["Cheap Thrills", "Chandelier", "Unstoppable"],
  "Avril Lavigne": ["Girlfriend", "Complicated", "Sk8er Boi"],
  "Carly Rae Jepsen": ["Call Me Maybe", "I Really Like You", "Good Time (with Owl City)"],
  "Meghan Trainor": ["Dear Future Husband", "Marry Me", "All About That Bass", "Lips Are Movin"],
  "One Direction": ["What Makes You Beautiful", "Story of My Life", "One Thing", "Live While We're Young"],
  "Westlife": ["You Raise Me Up", "My Love", "Beautiful in White?"],
  "Shane Filan": ["Beautiful in White"],
  "Backstreet Boys": ["I Want It That Way", "As Long As You Love Me", "Everybody"],
  "NSYNC": ["This I Promise You", "Bye Bye Bye"],
  "Boyz II Men": ["I'll Make Love to You", "End of the Road", "On Bended Knee"],
  "U2": ["Beautiful Day", "With or Without You"],
  "Oasis": ["Don't Look Back in Anger", "Whatever", "Stand by Me"],
  "The Black Eyed Peas": ["I Gotta Feeling", "Let's Get It Started", "Where Is the Love?"],
  "Pharrell Williams": ["Happy", "Get Lucky (Daft Punk feat.)"],
  "Mark Ronson": ["Uptown Funk (feat. Bruno Mars)"],
  "Daft Punk": ["One More Time", "Get Lucky", "Digital Love"],
  "Avicii": ["Wake Me Up", "Waiting for Love", "The Nights", "Without You"],
  "Zedd": ["Stay (with Alessia Cara)", "The Middle", "Clarity"],
  "Calvin Harris": ["Feel So Close", "This Is What You Came For", "Summer"],
  "David Guetta": ["Titanium (feat. Sia)", "Without You (feat. Usher)"],
  "The Chainsmokers": ["Closer", "Something Just Like This (with Coldplay)", "Paris", "Roses"],
  "Kygo": ["Firestone", "Stole the Show", "Higher Love"],
  "Clean Bandit": ["Rather Be", "Symphony", "Rockabye"],
  "Imagine Dragons": ["On Top Of The World", "It's Time", "Believer", "Thunder", "Follow You"],
  "American Authors": ["Best Day Of My Life", "Believer"],
  "OneRepublic": ["Counting Stars", "Good Life", "I Lived", "Sunshine"],
  "Owl City": ["Fireflies", "Good Time (with Carly Rae Jepsen)"],
  "Train": ["Marry Me", "Hey, Soul Sister", "Drops of Jupiter"],
  "MAGIC!": ["Rude"],
  "Jack Johnson": ["Better Together", "Banana Pancakes", "Upside Down"],
  "Tuck & Patti": ["Time After Time"],
  "Cyndi Lauper": ["Time After Time", "True Colors", "Girls Just Want to Have Fun"],
  "Madonna": ["Like a Prayer", "Cherish", "Holiday"],
  "Wham!": ["Last Christmas", "Wake Me Up Before You Go-Go", "Careless Whisper"],
  "George Michael": ["Faith", "Freedom! '90"],
  "Phil Collins": ["You'll Be in My Heart", "A Groovy Kind of Love", "True Colors?"],
  "Sting": ["Shape of My Heart", "Fields of Gold", "Every Breath You Take (The Police)"],
  "Bon Jovi": ["Livin' on a Prayer", "It's My Life", "Always", "Thank You for Loving Me"],
  "Aerosmith": ["I Don't Want to Miss a Thing", "Walk This Way", "Crazy"],
  "Bryan Adams": ["(Everything I Do) I Do It for You", "Heaven", "Summer of '69"],
  "Richard Marx": ["Right Here Waiting", "Now and Forever"],
  "Extreme": ["More Than Words"],
  "Mr. Big": ["To Be with You", "Wild World"],
  "Bette Midler": ["The Rose", "Wind Beneath My Wings"],
  "Bill Withers": ["Lovely Day", "Just the Two of Us (with Grover Washington Jr.)", "Lean on Me", "Ain't No Sunshine"],
  "James Taylor": ["How Sweet It Is (To Be Loved by You)", "You've Got a Friend"],
  "Van Morrison": ["Have I Told You Lately", "Moondance", "Brown Eyed Girl"],
  "Rod Stewart": ["Have I Told You Lately", "Sailing"],
  "The Archies": ["Sugar, Sugar"],
  "The Foundations": ["Build Me Up Buttercup"],
  "The Turtles": ["Happy Together"],
  "The Temptations": ["My Girl"],
  "The Supremes": ["You Can't Hurry Love", "Baby Love"],
  "Jackson 5": ["I Want You Back", "ABC", "I'll Be There"],
  "Ben E. King": ["Stand by Me"],
  "Marvin Gaye": ["How Sweet It Is?", "Ain't No Mountain High Enough (with Tammi Terrell)", "Let's Get It On"],
  "Aretha Franklin": ["Respect", "(You Make Me Feel Like) A Natural Woman"],
  "Otis Redding": ["Stand by Me?", "(Sittin' On) The Dock of the Bay"],
  "Sam Cooke": ["Wonderful World", "Cupid", "You Send Me"],
  "The Beach Boys": ["Wouldn't It Be Nice", "God Only Knows", "Surfin' U.S.A.", "Kokomo"],
  "Simon & Garfunkel": ["Bridge over Troubled Water", "The Sound of Silence", "Cecilia"],
  "John Denver": ["Take Me Home, Country Roads", "Annie's Song"],
  "Carole King": ["You've Got a Friend", "I Feel the Earth Move"],
  "Eagles": ["Desperado", "Hotel California"],
  "Chicago": ["Hard to Say I'm Sorry", "You're the Inspiration", "If You Leave Me Now"],
  "TOTO": ["Africa", "Rosanna", "Georgy Porgy"],
  "Boz Scaggs": ["We're All Alone", "Lowdown"],
  "Christopher Cross": ["Sailing", "Arthur's Theme (Best That You Can Do)"],
  "Sade": ["By Your Side", "Smooth Operator", "No Ordinary Love"],
  "Des'ree": ["Kissing You", "You Gotta Be"],
  "Corinne Bailey Rae": ["Put Your Records On", "Like a Star"],
  "Joss Stone": ["Spoiled", "Super Duper Love"],
  "Amy Winehouse": ["Valerie", "Tears Dry on Their Own"],
  "Duffy": ["Mercy", "Warwick Avenue"],
  "Bruno Major": ["Nothing", "Easily", "The Most Beautiful Thing"],
  "Lauv": ["I Like Me Better", "Paris in the Rain", "Steal the Show"],
  "LANY": ["ILYSB", "Malibu Nights"],
  "Surfaces": ["Sunday Best", "Wave of You"],
  "HONNE": ["Day 1 ◑", "Location Unknown ◐", "Crying Over You"],
  "Lukas Graham": ["7 Years", "Love Someone", "Happy Home"],
  "James Arthur": ["Say You Won't Let Go", "Falling like the Stars", "Train Wreck"],
  "Calum Scott": ["You Are the Reason", "Dancing On My Own", "Heaven"],
  "Lewis Capaldi": ["Someone You Loved", "Before You Go"],
  "Tom Odell": ["Another Love", "Grow Old with Me", "Real Love"],
  "Passenger": ["Let Her Go", "Anywhere"],
  "Kodaline": ["The One", "All I Want", "High Hopes"],
  "Dan + Shay": ["Speechless", "From the Ground Up", "10,000 Hours (with Justin Bieber)"],
  "Thomas Rhett": ["Die a Happy Man", "Marry Me"],
  "Brett Young": ["In Case You Didn't Know", "Mercy"],
  "Russell Dickerson": ["Yours", "Love You Like I Used To"],
  "Shania Twain": ["You're Still the One", "From This Moment On", "Man! I Feel Like a Woman!"],
  "Faith Hill": ["This Kiss", "Breathe"],
  "LeAnn Rimes": ["How Do I Live", "Can't Fight the Moonlight"],
  "Carrie Underwood": ["Mama's Song", "Before He Cheats"],
  "Kacey Musgraves": ["Butterflies", "Golden Hour"],
  "Ingrid Michaelson": ["The Way I Am", "You and I", "Can't Help Falling in Love"],
  "Sara Bareilles": ["I Choose You", "Love Song", "Brave"],
  "Regina Spektor": ["Us", "Fidelity"],
  "Feist": ["1234", "Mushaboom"],
  "Lenka": ["The Show", "Everything at Once", "Blue Skies"],
  "Priscilla Ahn": ["Dream", "Fine on the Outside"],
  "Yael Naim": ["New Soul"],
  "Israel Kamakawiwo'ole": ["Over the Rainbow / What a Wonderful World"],
  "Jake Shimabukuro": ["Bohemian Rhapsody (ukulele)", "While My Guitar Gently Weeps (ukulele)"],
  "Bic Runga": ["Sway"],
  "Emilia": ["Big Big World"],
  "M2M": ["Pretty Boy", "The Day You Went Away"],
  "A*Teens": ["Upside Down"],
  "Carly Simon?": [],
  "Aqua": ["Barbie Girl", "Lollipop (Candyman)"],
  "Jamiroquai": ["Virtual Insanity", "Canned Heat", "Love Foolosophy"],
  "Incognito": ["Everyday", "Still a Friend of Mine"],
  "Level 42": ["Lessons in Love", "Something About You"],
  "Culture Club": ["Karma Chameleon"],
  "Duran Duran": ["Rio", "Ordinary World"],
  "a-ha": ["Take On Me"],
  "Rick Astley": ["Never Gonna Give You Up", "Together Forever"],
  "Bananarama": ["Venus"],
  "Belinda Carlisle": ["Heaven Is a Place on Earth", "Circle in the Sand"],
  "Roxette": ["It Must Have Been Love", "Listen to Your Heart"],
  "The Cardigans": ["Lovefool", "Carnival"],
  "Sixpence?": [],
  "Natalie Cole": ["This Will Be (An Everlasting Love)", "Unforgettable (with Nat King Cole)", "L-O-V-E"],
  "Diana Ross": ["If We Hold On Together", "Endless Love (with Lionel Richie)", "Ain't No Mountain High Enough"],
  "Donna Summer": ["Hot Stuff", "Last Dance"],
  "Gloria Gaynor": ["I Will Survive", "Can't Take My Eyes Off You"],
  "Frankie Valli": ["Can't Take My Eyes Off You"],
  "Barry White": ["You're the First, the Last, My Everything", "Can't Get Enough of Your Love, Babe"],
  "The Commodores": ["Three Times a Lady", "Easy"],
  "Cheryl Lynn": ["Got to Be Real"],
  "Sister Sledge": ["We Are Family"],
  "Chic": ["Le Freak", "Good Times"],
  "Wild Cherry": ["Play That Funky Music"],
  "KC and the Sunshine Band": ["That's the Way (I Like It)", "Boogie Shoes"],
  "Jackson Sisters": ["I Believe in Miracles"],
  "Tavares": ["Heaven Must Be Missing an Angel"],
  "Rose Royce": ["Car Wash"],
  "Anderson .Paak": ["Come Home", "Make It Better"],
  "Silk Sonic": ["Leave the Door Open", "Smokin Out the Window", "Skate"],
  "Dua Lipa": ["Levitating", "Dance the Night", "Don't Start Now"],
  "Harry Styles": ["Watermelon Sugar", "Adore You", "As It Was", "Late Night Talking"],
  "Niall Horan": ["This Town", "Slow Hands"],
  "Olivia Rodrigo": ["good 4 u", "deja vu"],
  "Billie Eilish": ["Ocean Eyes", "What Was I Made For?"],
  "Doja Cat": ["Say So", "Kiss Me More"],
  "Lizzo": ["Good as Hell", "About Damn Time", "Juice"],
  "Post Malone": ["Sunflower (with Swae Lee)", "Circles"],
  "Khalid": ["Talk", "Better", "Young Dumb & Broke"],
  "Benson Boone": ["Beautiful Things", "In the Stars"],
  "Teddy Swims": ["Lose Control", "The Door"],
  "Stephen Sanchez": ["Until I Found You"],
  "d4vd": ["Here With Me", "Romantic Homicide"],
  "JVKE": ["golden hour"],
  "Em Beihold": ["Numb Little Bug"],
  "Meghan Trainor & Seth MacFarlane?": [],
  "Laufey": ["From the Start", "Falling Behind", "Valentine"],
  "Conan Gray": ["Heather", "Memories"],
  "Alec Benjamin": ["Let Me Down Slowly", "If We Have Each Other"],
  "Anne-Marie": ["2002", "FRIENDS", "Beautiful"],
  "Rita Ora": ["Anywhere", "Your Song", "Let You Love Me"],
  "Jess Glynne": ["Hold My Hand", "I'll Be There", "Rather Be (with Clean Bandit)"],
  "Ellie Goulding": ["Love Me like You Do", "Burn", "How Long Will I Love You", "Still Falling for You"],
  "Rachel Platten": ["Fight Song", "Stand by You"],
  "Andy Grammer": ["Honey, I'm Good.", "Fresh Eyes", "Don't Give Up on Me"],
  "Ben Rector": ["Brand New", "Love Like This"],
  "Matt Wertz?": [],
  "Phillip Phillips": ["Home", "Gone, Gone, Gone"],
  "Vance Joy": ["Riptide", "I'm with You", "Fire and the Flood"],
  "George Ezra": ["Budapest", "Paradise", "Shotgun", "Hold My Girl"],
  "James Bay": ["Hold Back the River", "Let It Go", "Us"],
  "Hozier": ["Take Me to Church", "Cherry Wine", "Almost (Sweet Music)"],
  "The Lumineers": ["Ho Hey", "Ophelia", "Stubborn Love"],
  "Mumford & Sons": ["I Will Wait", "Little Lion Man"],
  "Of Monsters and Men": ["Little Talks", "Dirty Paws"],
  "The Script": ["Superheroes", "Hall of Fame", "Breakeven"],
  "Snow Patrol": ["Chasing Cars", "Run", "Just Say Yes"],
  "Keane": ["Somewhere Only We Know", "Everybody's Changing"],
  "Travis": ["Sing", "Closer", "Flowers in the Window"],
  "The Fray": ["How to Save a Life", "Look After You", "Never Say Never"],
  "Lifehouse": ["You and Me", "Everything", "Whatever It Takes"],
  "Goo Goo Dolls": ["Iris", "Slide", "Better Days"],
  "Matchbox Twenty": ["3AM", "Push", "Overjoyed"],
  "Rob Thomas": ["Little Wonders", "Smooth (with Santana)"],
  "The Corrs": ["Breathless", "Runaway", "What Can I Do"],
  "The Cranberries": ["Dreams", "Linger", "Ode to My Family"],
  "Sheryl Crow": ["All I Wanna Do", "Soak Up the Sun", "The First Cut Is the Deepest"],
  "Natasha Bedingfield": ["Unwritten", "Pocketful of Sunshine", "These Words"],
  "Michelle Branch": ["Everywhere", "All You Wanted", "The Game of Love (with Santana)"],
  "Kelly Clarkson": ["Stronger", "A Moment Like This", "Breakaway", "My Life Would Suck Without You"],
  "Demi Lovato": ["Let It Go?", "Skyscraper", "Give Your Heart a Break"],
  "Selena Gomez": ["Love You like a Love Song", "Rare", "Who Says"],
  "Miley Cyrus": ["Party in the U.S.A.", "The Climb", "Malibu", "Flowers"],
  "Jonas Brothers": ["Sucker", "What a Man Gotta Do", "Only Human"],
  "Fifth Harmony": ["Worth It", "That's My Girl"],
  "Little Mix": ["Black Magic", "Shout Out to My Ex", "Touch"],
  "Camila Cabello": ["Havana", "Never Be the Same", "Señorita (with Shawn Mendes)"],
  "Halsey": ["Without Me", "Colors"],
  "Bebe Rexha": ["Meant to Be (with Florida Georgia Line)", "I'm Good (Blue) (with David Guetta)"],
  "Florida Georgia Line": ["H.O.L.Y.", "Cruise", "Meant to Be (with Bebe Rexha)"],
  "Pitbull": ["Time of Our Lives (with Ne-Yo)", "Give Me Everything", "International Love", "Timber (feat. Kesha)"],
  "Ne-Yo": ["Miss Independent", "Closer", "So Sick"],
  "Usher": ["DJ Got Us Fallin' in Love", "Yeah!", "U Got It Bad"],
  "Chris Brown": ["Forever", "With You", "Under the Influence"],
  "Jay Sean": ["Down", "Do You Remember"],
  "Iyaz": ["Replay"],
  "Sean Kingston": ["Beautiful Girls", "Fire Burning"],
  "Jason Derulo": ["Want to Want Me", "Trumpets", "Marry Me", "Savage Love"],
  "Flo Rida": ["Good Feeling", "Club Can't Handle Me", "Whistle", "My House"],
  "will.i.am": ["This Is Love (feat. Eva Simons)", "Feelin' Myself?"],
  "LMFAO": ["Party Rock Anthem", "Sexy and I Know It"],
  "Macklemore & Ryan Lewis": ["Can't Hold Us", "Same Love"],
  "Meduza": ["Piece of Your Heart"],
  "Jonas Blue": ["Perfect Strangers", "Mama", "Rise"],
  "Sigala": ["Easy Love", "Sweet Lovin'", "Came Here for Love"],
  "Robin Schulz": ["Sugar (feat. Francesco Yates)", "Prayer in C (remix)"],
  "Felix Jaehn": ["Ain't Nobody (Loves Me Better)", "Cheerleader (OMI remix)"],
  "OMI": ["Cheerleader", "Hula Hoop"],
  "Matoma": ["Old Thing Back", "False Alarm"],
  "Lost Frequencies": ["Are You with Me", "Reality", "Where Are You Now"],
  "Alan Walker": ["Faded", "Alone", "Sing Me to Sleep"],
  "Marshmello": ["Happier (with Bastille)", "Alone", "Silence (feat. Khalid)"],
  "Bastille": ["Pompeii", "Happier (with Marshmello)", "Good Grief"],
  "Galantis": ["Runaway (U & I)", "No Money", "Peanut Butter Jelly"],
  "Major Lazer": ["Lean On", "Cold Water", "Light It Up"],
  "DJ Snake": ["Let Me Love You (feat. Justin Bieber)", "Taki Taki"],
  "Martin Garrix": ["In the Name of Love (with Bebe Rexha)", "Animals", "Scared to Be Lonely"],
  "Tiësto": ["The Business", "Red Lights", "Wasted"],
  "Swedish House Mafia": ["Don't You Worry Child", "Save the World"],
  "Axwell Λ Ingrosso": ["More Than You Know", "Sun Is Shining"],
  "Sigrid": ["Strangers", "Don't Kill My Vibe"],
  "Zara Larsson": ["Lush Life", "Symphony (with Clean Bandit)", "Never Forget You"],
  "Tove Lo": ["Habits (Stay High)", "Talking Body"],
  "MØ": ["Final Song", "Lean On (with Major Lazer)"],
  "Astrid S": ["Hurts So Good", "Think Before I Talk"],
  "Dagny": ["Love You Like That", "Somebody"],
};

// ================= 映画・ディズニー・ジブリ・アニメ =================
const THEMES = [
  // ディズニー
  ["A Whole New World", "『アラジン』より"], ["Beauty and the Beast", "『美女と野獣』より"],
  ["Can You Feel the Love Tonight", "『ライオン・キング』より"], ["Circle of Life", "『ライオン・キング』より"],
  ["Let It Go", "『アナと雪の女王』より"], ["Love Is an Open Door", "『アナと雪の女王』より"],
  ["生まれてはじめて", "『アナと雪の女王』より"], ["Into the Unknown", "『アナと雪の女王2』より"],
  ["Part of Your World", "『リトル・マーメイド』より"], ["Under the Sea", "『リトル・マーメイド』より"],
  ["Kiss the Girl", "『リトル・マーメイド』より"], ["When You Wish upon a Star", "『ピノキオ』より"],
  ["A Dream Is a Wish Your Heart Makes", "『シンデレラ』より"], ["So This Is Love", "『シンデレラ』より"],
  ["Once Upon a Dream", "『眠れる森の美女』より"], ["Tale as Old as Time?", "『美女と野獣』より"],
  ["How Far I'll Go", "『モアナと伝説の海』より"], ["You're Welcome", "『モアナと伝説の海』より"],
  ["Remember Me", "『リメンバー・ミー』より"], ["Un Poco Loco", "『リメンバー・ミー』より"],
  ["When She Loved Me", "『トイ・ストーリー2』より"], ["You've Got a Friend in Me", "『トイ・ストーリー』より"],
  ["I See the Light", "『塔の上のラプンツェル』より"], ["When Will My Life Begin", "『塔の上のラプンツェル』より"],
  ["Something There", "『美女と野獣』より"], ["Belle", "『美女と野獣』より"],
  ["Friend Like Me", "『アラジン』より"], ["Speechless", "『アラジン(実写)』より"],
  ["Try Everything", "『ズートピア』より"], ["Lava", "『ピクサー短編 LAVA』より"],
  ["Married Life", "『カールじいさんの空飛ぶ家』より"], ["Touch the Sky", "『メリダとおそろしの森』より"],
  ["Dos Oruguitas", "『ミラベルと魔法だらけの家』より"], ["We Don't Talk About Bruno", "『ミラベルと魔法だらけの家』より"],
  ["The Bare Necessities", "『ジャングル・ブック』より"], ["Supercalifragilisticexpialidocious", "『メリー・ポピンズ』より"],
  ["Chim Chim Cher-ee", "『メリー・ポピンズ』より"], ["It's a Small World", "ディズニー・テーマパークより"],
  ["Mickey Mouse March", "ディズニーより"], ["Zip-a-Dee-Doo-Dah", "ディズニーより"],
  ["Electrical Parade", "ディズニー・テーマパークより"],
  // ジブリ
  ["君をのせて", "『天空の城ラピュタ』より"], ["となりのトトロ", "『となりのトトロ』より"],
  ["さんぽ", "『となりのトトロ』より"], ["風の通り道", "『となりのトトロ』より"],
  ["海の見える街", "『魔女の宅急便』より"], ["やさしさに包まれたなら", "『魔女の宅急便』より"],
  ["ルージュの伝言", "『魔女の宅急便』より"], ["カントリー・ロード", "『耳をすませば』より"],
  ["いつも何度でも", "『千と千尋の神隠し』より"], ["あの夏へ", "『千と千尋の神隠し』より"],
  ["人生のメリーゴーランド", "『ハウルの動く城』より"], ["世界の約束", "『ハウルの動く城』より"],
  ["崖の上のポニョ", "『崖の上のポニョ』より"], ["旅立ち", "『魔女の宅急便』より"],
  ["もののけ姫", "『もののけ姫』より"], ["アシタカせっ記", "『もののけ姫』より"],
  ["ナウシカ・レクイエム", "『風の谷のナウシカ』より"], ["鳥の人", "『風の谷のナウシカ』より"],
  ["テルーの唄", "『ゲド戦記』より"], ["Arrietty's Song", "『借りぐらしのアリエッティ』より"],
  ["ひこうき雲", "『風立ちぬ』より"], ["かぐや姫の物語 主題歌「いのちの記憶」", "『かぐや姫の物語』より"],
  // 映画・ミュージカル
  ["My Heart Will Go On", "『タイタニック』より"], ["A Time for Us", "『ロミオとジュリエット』より"],
  ["Kissing You", "『ロミオ＋ジュリエット』より"], ["Moon River", "『ティファニーで朝食を』より"],
  ["Singin' in the Rain", "『雨に唄えば』より"], ["Cheek to Cheek", "『トップ・ハット』より"],
  ["Over the Rainbow", "『オズの魔法使』より"], ["Edelweiss", "『サウンド・オブ・ミュージック』より"],
  ["My Favorite Things", "『サウンド・オブ・ミュージック』より"], ["Do-Re-Mi", "『サウンド・オブ・ミュージック』より"],
  ["Climb Ev'ry Mountain", "『サウンド・オブ・ミュージック』より"], ["Tonight", "『ウエスト・サイド物語』より"],
  ["Somewhere", "『ウエスト・サイド物語』より"], ["Maria", "『ウエスト・サイド物語』より"],
  ["Memory", "ミュージカル『キャッツ』より"], ["All I Ask of You", "『オペラ座の怪人』より"],
  ["Think of Me", "『オペラ座の怪人』より"], ["The Music of the Night", "『オペラ座の怪人』より"],
  ["I Dreamed a Dream", "『レ・ミゼラブル』より"], ["On My Own", "『レ・ミゼラブル』より"],
  ["Seasons of Love", "ミュージカル『RENT』より"], ["Defying Gravity", "ミュージカル『ウィキッド』より"],
  ["For Good", "ミュージカル『ウィキッド』より"], ["The Greatest Show", "『グレイテスト・ショーマン』より"],
  ["A Million Dreams", "『グレイテスト・ショーマン』より"], ["This Is Me", "『グレイテスト・ショーマン』より"],
  ["Rewrite the Stars", "『グレイテスト・ショーマン』より"], ["Never Enough", "『グレイテスト・ショーマン』より"],
  ["City of Stars", "『ラ・ラ・ランド』より"], ["Another Day of Sun", "『ラ・ラ・ランド』より"],
  ["Mia & Sebastian's Theme", "『ラ・ラ・ランド』より"], ["Shallow", "『アリー/ スター誕生』より"],
  ["Mrs. Robinson", "『卒業』より"], ["Raindrops Keep Fallin' on My Head", "『明日に向って撃て!』より"],
  ["Up Where We Belong", "『愛と青春の旅だち』より"], ["Take My Breath Away", "『トップガン』より"],
  ["Danger Zone", "『トップガン』より"], ["Footloose", "『フットルース』より"],
  ["Flashdance... What a Feeling", "『フラッシュダンス』より"], ["The Time of My Life", "『ダーティ・ダンシング』より"],
  ["Unchained Melody", "『ゴースト/ニューヨークの幻』より"], ["Pretty Woman", "『プリティ・ウーマン』より"],
  ["It Must Have Been Love", "『プリティ・ウーマン』より"], ["I Say a Little Prayer", "『ベスト・フレンズ・ウェディング』より"],
  ["How Deep Is Your Love?", "『サタデー・ナイト・フィーバー』より"], ["Eye of the Tiger", "『ロッキー3』より"],
  ["Gonna Fly Now", "『ロッキー』より"], ["Star Wars Main Title", "『スター・ウォーズ』より"],
  ["Imperial March", "『スター・ウォーズ』より"], ["Raiders March", "『インディ・ジョーンズ』より"],
  ["Back to the Future Theme", "『バック・トゥ・ザ・フューチャー』より"], ["Hedwig's Theme", "『ハリー・ポッター』より"],
  ["He's a Pirate", "『パイレーツ・オブ・カリビアン』より"], ["Mission: Impossible Theme", "『ミッション:インポッシブル』より"],
  ["James Bond Theme", "『007』シリーズより"], ["Rocky Theme?", "『ロッキー』より"],
  ["The Pink Panther Theme", "『ピンクパンサー』より"], ["Baby Elephant Walk", "『ハタリ!』より"],
  ["Gabriel's Oboe", "『ミッション』より"], ["Cinema Paradiso (Love Theme)", "『ニュー・シネマ・パラダイス』より"],
  ["Il Postino", "『イル・ポスティーノ』より"], ["La Vie En Rose", "シャンソン・映画より"],
  ["Les Champs-Élysées（オー・シャンゼリゼ）", "シャンソンより"], ["愛の讃歌", "シャンソンより"],
  ["Sway (Quien Será)", "ラテン・スタンダード"], ["Bésame Mucho", "ラテン・スタンダード"],
  ["Quizás, Quizás, Quizás", "ラテン・スタンダード"], ["Mas Que Nada", "ボサノバ・スタンダード"],
  ["The Girl from Ipanema（イパネマの娘）", "ボサノバ・スタンダード"], ["Wave", "ボサノバ・スタンダード"],
  ["Corcovado", "ボサノバ・スタンダード"], ["Águas de Março（三月の水）", "ボサノバ・スタンダード"],
  // 邦画・アニメ・ドラマ
  ["ルパン三世のテーマ", "『ルパン三世』より"], ["銀河鉄道999", "『銀河鉄道999』より"],
  ["残酷な天使のテーゼ", "『新世紀エヴァンゲリオン』より"], ["ムーンライト伝説", "『美少女戦士セーラームーン』より"],
  ["CAT'S EYE", "『キャッツ・アイ』より"], ["タッチ", "『タッチ』より"],
  ["ドラえもんのうた", "『ドラえもん』より"], ["アンパンマンのマーチ", "『それいけ!アンパンマン』より"],
  ["サザエさん一家", "『サザエさん』より"], ["おどるポンポコリン", "『ちびまる子ちゃん』より"],
  ["勇気100%", "『忍たま乱太郎』より"], ["WAになっておどろう?", "『みんなのうた』より"],
  ["ウィーアー!", "『ONE PIECE』より"], ["ビンクスの酒", "『ONE PIECE』より"],
  ["紅蓮華", "『鬼滅の刃』より"], ["炎", "『鬼滅の刃 無限列車編』より"],
  ["明け星", "『鬼滅の刃 無限列車編(TV)』より"], ["絆ノ奇跡", "『鬼滅の刃 刀鍛冶の里編』より"],
  ["アイドル", "『推しの子』より"], ["新時代", "『ONE PIECE FILM RED』より"],
  ["ミックスナッツ", "『SPY×FAMILY』より"], ["喜劇", "『SPY×FAMILY』より"],
  ["残響散歌", "『鬼滅の刃 遊郭編』より"], ["廻廻奇譚", "『呪術廻戦』より"],
  ["青のすみか", "『呪術廻戦 懐玉・玉折』より"], ["SPECIALZ", "『呪術廻戦 渋谷事変』より"],
  ["君の知らない物語", "『化物語』より"], ["secret base 〜君がくれたもの〜", "『あの花』より"],
  ["Butter-Fly", "『デジモンアドベンチャー』より"], ["Get Wild", "『シティーハンター』より"],
  ["Love Story?", "ドラマ主題歌より"], ["ラヴ・ストーリーは突然に", "『東京ラブストーリー』より"],
  ["SAY YES", "『101回目のプロポーズ』より"], ["逢いたくていま", "『JIN-仁-』より"],
  ["HERO", "『HERO』より"], ["Precious", "『ドラマ主題歌』より"],
];

// ================= ジャズ・スタンダード =================
const JAZZ = [
  "Fly Me to the Moon", "The Way You Look Tonight", "L-O-V-E", "Cheek to Cheek", "Misty",
  "Autumn Leaves（枯葉）", "All of Me", "But Not for Me", "Someone to Watch Over Me", "'S Wonderful",
  "Embraceable You", "Our Love Is Here to Stay", "I Got Rhythm", "Summertime", "My Funny Valentine",
  "My Romance", "Blue Moon", "Isn't It Romantic?", "The Nearness of You", "Stardust",
  "Georgia on My Mind", "It Had to Be You", "Dream a Little Dream of Me", "When I Fall in Love",
  "Unforgettable", "Smile", "What a Diff'rence a Day Made", "Tea for Two", "Night and Day",
  "I've Got You Under My Skin", "Ev'ry Time We Say Goodbye", "So in Love", "Begin the Beguine",
  "You'd Be So Nice to Come Home To", "All the Things You Are", "The Very Thought of You",
  "In a Sentimental Mood", "Satin Doll", "Take the \"A\" Train", "Mood Indigo", "Sophisticated Lady",
  "Don't Get Around Much Anymore", "It Don't Mean a Thing", "Caravan", "Sing, Sing, Sing",
  "In the Mood", "Moonlight Serenade", "A String of Pearls", "Take Five", "Waltz for Debby",
  "My Foolish Heart", "Someday My Prince Will Come", "On the Sunny Side of the Street",
  "Ain't Misbehavin'", "Honeysuckle Rose", "Sweet Georgia Brown", "Bye Bye Blackbird",
  "There Will Never Be Another You", "I'll Be Seeing You", "These Foolish Things",
  "The Shadow of Your Smile", "Days of Wine and Roses", "Charade", "Dear Heart",
  "Moon River", "What Are You Doing the Rest of Your Life?", "The Summer Knows（おもいでの夏）",
  "Alfie", "The Look of Love", "Close to You?", "This Guy's in Love with You",
  "Wives and Lovers", "I Say a Little Prayer", "Walk On By", "What the World Needs Now Is Love",
  "Cantaloupe Island", "Watermelon Man", "Maiden Voyage", "Blue Bossa", "Song for My Father",
  "The Sidewinder", "Moanin'", "Work Song", "Sugar", "Mercy, Mercy, Mercy",
  "Feel Like Makin' Love", "Just the Two of Us", "Street Life", "Rise", "Breezin'",
  "This Masquerade", "Affirmation", "Winelight", "Mister Magic", "Morning Dance",
  "Spain", "500 Miles High", "La Fiesta", "Birdland", "A Remark You Made",
  "Cute", "Li'l Darlin'", "April in Paris", "Corner Pocket", "Shiny Stockings",
  "Splanky", "One O'Clock Jump", "Jumpin' at the Woodside", "Basie Straight Ahead?",
  "Sway?", "Perhaps, Perhaps, Perhaps", "Cheek to Cheek?", "Beyond the Sea",
  "Come Fly with Me", "That's Amore", "Volare", "Mack the Knife", "Ain't That a Kick in the Head",
  "Everybody Loves Somebody", "You Make Me Feel So Young", "Witchcraft", "Strangers in the Night",
  "New York, New York", "Love", "Almost Like Being in Love", "On the Street Where You Live",
  "I Could Have Danced All Night", "If I Were a Bell", "Just in Time", "The Best Is Yet to Come",
  "Orange Colored Sky", "Route 66", "Straighten Up and Fly Right", "Paper Moon（It's Only a Paper Moon）",
  "Pennies from Heaven", "Blue Skies", "Puttin' On the Ritz", "Steppin' Out with My Baby",
  "I've Got the World on a String", "Get Happy", "Over the Rainbow?", "Come Rain or Come Shine",
  "That Old Black Magic", "Accentuate the Positive", "Dream", "Sentimental Journey",
];

// ================= クラシック・讃美歌・セレモニー定番 =================
const CLASSICAL = [
  ["カノン ニ長調", "Pachelbel"], ["主よ、人の望みの喜びよ", "J.S. Bach"],
  ["G線上のアリア", "J.S. Bach"], ["ブランデンブルク協奏曲 第5番 第1楽章", "J.S. Bach"],
  ["ブランデンブルク協奏曲 第3番 第1楽章", "J.S. Bach"], ["トッカータとフーガ ニ短調", "J.S. Bach"],
  ["アヴェ・マリア（バッハ/グノー）", "Bach/Gounod"], ["羊は安らかに草を食み", "J.S. Bach"],
  ["アヴェ・マリア", "Schubert"], ["セレナーデ", "Schubert"], ["野ばら", "Schubert"],
  ["楽興の時 第3番", "Schubert"], ["ピアノ五重奏曲「ます」第4楽章", "Schubert"],
  ["結婚行進曲（真夏の夜の夢）", "Mendelssohn"], ["春の歌", "Mendelssohn"],
  ["ヴァイオリン協奏曲 ホ短調 第1楽章", "Mendelssohn"],
  ["婚礼の合唱（ローエングリン）", "Wagner"], ["ワルキューレの騎行", "Wagner"],
  ["アヴェ・マリア", "Caccini"], ["アメイジング・グレイス", "讃美歌"],
  ["いつくしみ深き", "讃美歌312番"], ["主われを愛す", "讃美歌461番"],
  ["カントリーロード?", "讃美歌?"], ["きよしこの夜", "讃美歌"],
  ["もろびとこぞりて", "讃美歌"], ["ハレルヤ・コーラス（メサイア）", "Handel"],
  ["オンブラ・マイ・フ（ラルゴ）", "Handel"], ["水上の音楽 アラ・ホーンパイプ", "Handel"],
  ["王宮の花火の音楽", "Handel"], ["サラバンド", "Handel"],
  ["トランペット・ヴォランタリー", "Clarke"], ["トランペット・チューン", "Purcell"],
  ["威風堂々 第1番", "Elgar"], ["愛の挨拶", "Elgar"], ["ニムロッド（エニグマ変奏曲）", "Elgar"],
  ["木星（組曲「惑星」より）", "Holst"], ["アイネ・クライネ・ナハトムジーク 第1楽章", "Mozart"],
  ["ピアノ協奏曲第21番 第2楽章", "Mozart"], ["トルコ行進曲", "Mozart"],
  ["フィガロの結婚 序曲", "Mozart"], ["ディヴェルティメント K.136 第1楽章", "Mozart"],
  ["きらきら星変奏曲", "Mozart"], ["ピアノソナタ第11番 K.331", "Mozart"],
  ["レクイエムより「ラクリモサ」", "Mozart"], ["クラリネット協奏曲 第2楽章", "Mozart"],
  ["エリーゼのために", "Beethoven"], ["月光ソナタ 第1楽章", "Beethoven"],
  ["悲愴ソナタ 第2楽章", "Beethoven"], ["交響曲第7番 第1楽章", "Beethoven"],
  ["交響曲第9番「歓喜の歌」", "Beethoven"], ["ピアノソナタ「テンペスト」第3楽章", "Beethoven"],
  ["ロマンス 第2番", "Beethoven"], ["トルコ行進曲（アテネの廃墟）", "Beethoven"],
  ["ノクターン 第2番 変ホ長調", "Chopin"], ["幻想即興曲", "Chopin"],
  ["別れの曲", "Chopin"], ["子犬のワルツ", "Chopin"], ["華麗なる大円舞曲", "Chopin"],
  ["雨だれの前奏曲", "Chopin"], ["英雄ポロネーズ", "Chopin"], ["バラード第1番", "Chopin"],
  ["ワルツ第7番 嬰ハ短調", "Chopin"], ["revolutionary étude（革命）", "Chopin"],
  ["愛の夢 第3番", "Liszt"], ["ラ・カンパネラ", "Liszt"], ["ハンガリー狂詩曲第2番", "Liszt"],
  ["トロイメライ", "Schumann"], ["献呈", "Schumann"],
  ["ハンガリー舞曲第5番", "Brahms"], ["ワルツ第15番", "Brahms"], ["子守歌", "Brahms"],
  ["交響曲第1番 第4楽章", "Brahms"],
  ["花のワルツ（くるみ割り人形）", "Tchaikovsky"], ["白鳥の湖 情景", "Tchaikovsky"],
  ["眠れる森の美女 ワルツ", "Tchaikovsky"], ["ピアノ協奏曲第1番 第1楽章", "Tchaikovsky"],
  ["くるみ割り人形「金平糖の踊り」", "Tchaikovsky"], ["弦楽セレナーデ 第1楽章", "Tchaikovsky"],
  ["アンダンテ・カンタービレ", "Tchaikovsky"],
  ["新世界より 第2楽章（家路）", "Dvořák"], ["新世界より 第4楽章", "Dvořák"],
  ["ユーモレスク", "Dvořák"], ["わが母の教え給いし歌", "Dvořák"],
  ["ヴォカリーズ", "Rachmaninoff"], ["ピアノ協奏曲第2番 第1楽章", "Rachmaninoff"],
  ["パガニーニの主題による狂詩曲 第18変奏", "Rachmaninoff"],
  ["月の光", "Debussy"], ["アラベスク第1番", "Debussy"], ["夢（Rêverie）", "Debussy"],
  ["亜麻色の髪の乙女", "Debussy"], ["ベルガマスク組曲 パスピエ", "Debussy"],
  ["ジムノペディ第1番", "Satie"], ["ジュ・トゥ・ヴ（あなたが欲しい）", "Satie"],
  ["グノシエンヌ第1番", "Satie"],
  ["亡き王女のためのパヴァーヌ", "Ravel"], ["ボレロ", "Ravel"], ["水の戯れ", "Ravel"],
  ["シシリエンヌ", "Fauré"], ["パヴァーヌ", "Fauré"], ["夢のあとに", "Fauré"], ["レクイエムより「ピエ・イエズ」", "Fauré"],
  ["タイスの瞑想曲", "Massenet"], ["カルメン 前奏曲", "Bizet"], ["ハバネラ（カルメン）", "Bizet"],
  ["アルルの女 メヌエット", "Bizet"], ["真珠採りのタンゴ?", "Bizet"],
  ["誰も寝てはならぬ（トゥーランドット）", "Puccini"], ["私のお父さん（ジャンニ・スキッキ）", "Puccini"],
  ["ある晴れた日に（蝶々夫人）", "Puccini"], ["乾杯の歌（椿姫）", "Verdi"],
  ["凱旋行進曲（アイーダ）", "Verdi"], ["女心の歌（リゴレット）", "Verdi"],
  ["時の踊り（ジョコンダ）", "Ponchielli"], ["カヴァレリア・ルスティカーナ 間奏曲", "Mascagni"],
  ["四季より「春」第1楽章", "Vivaldi"], ["四季より「夏」第3楽章", "Vivaldi"],
  ["四季より「秋」第1楽章", "Vivaldi"], ["四季より「冬」第2楽章", "Vivaldi"],
  ["2つのマンドリンのための協奏曲", "Vivaldi"], ["グローリア", "Vivaldi"],
  ["アルビノーニのアダージョ", "Albinoni"], ["ジュピター?", "Handel?"],
  ["精霊の踊り", "Gluck"], ["アヴェ・ヴェルム・コルプス", "Mozart"],
  ["カルメン 闘牛士の歌", "Bizet"], ["天国と地獄 序曲", "Offenbach"],
  ["美しく青きドナウ", "J. Strauss II"], ["春の声", "J. Strauss II"],
  ["皇帝円舞曲", "J. Strauss II"], ["ウィーンの森の物語", "J. Strauss II"],
  ["ラデツキー行進曲", "J. Strauss I"], ["金と銀", "Lehár"], ["メリー・ウィドウ・ワルツ", "Lehár"],
  ["スケーターズ・ワルツ", "Waldteufel"], ["女学生（ワルツ）", "Waldteufel"],
  ["乙女の祈り", "Badarzewska"], ["紡ぎ歌", "Ellmenreich"],
  ["ラ・パロマ", "Yradier"], ["エストレリータ", "Ponce"],
  ["剣の舞", "Khachaturian"], ["仮面舞踏会 ワルツ", "Khachaturian"],
  ["だったん人の踊り", "Borodin"], ["展覧会の絵 プロムナード", "Mussorgsky"],
  ["熊蜂の飛行", "Rimsky-Korsakov"], ["シェヘラザード 第3楽章", "Rimsky-Korsakov"],
  ["ペール・ギュント「朝」", "Grieg"], ["ソルヴェイグの歌", "Grieg"], ["ピアノ協奏曲 イ短調 第1楽章", "Grieg"],
  ["フィンランディア", "Sibelius"], ["カレリア組曲 行進曲風に", "Sibelius"],
  ["アランフェス協奏曲 第2楽章", "Rodrigo"], ["禁じられた遊び（愛のロマンス）", "スペイン民謡"],
  ["アルハンブラの思い出", "Tárrega"], ["カヴァティーナ", "Myers"],
  ["ニュー・シネマ・パラダイス「愛のテーマ」", "Morricone"], ["ネッラ・ファンタジア", "Morricone"],
  ["ガブリエルのオーボエ", "Morricone"], ["海の上のピアニスト「愛を奏でて」", "Morricone"],
  ["戦場のメリークリスマス", "坂本龍一"], ["energy flow", "坂本龍一"], ["Merry Christmas Mr. Lawrence?", "坂本龍一"],
  ["Summer", "久石譲"], ["あの夏へ?", "久石譲"], ["Oriental Wind", "久石譲"],
  ["Asian Dream Song", "久石譲"], ["Stand Alone（坂の上の雲）", "久石譲"],
  ["情熱大陸", "葉加瀬太郎"], ["エトピリカ", "葉加瀬太郎"], ["ひまわり", "葉加瀬太郎"],
  ["Another Sky", "葉加瀬太郎"], ["万讃歌", "葉加瀬太郎"],
  ["ルパン三世のテーマ '78?", "大野雄二"], ["ラプソディ・イン・ブルー", "Gershwin"],
  ["パリのアメリカ人", "Gershwin"], ["サマータイム?", "Gershwin"],
  ["シンコペーテッド・クロック", "L. Anderson"], ["そりすべり", "L. Anderson"],
  ["トランペット吹きの休日", "L. Anderson"], ["タイプライター", "L. Anderson"],
  ["ブルー・タンゴ", "L. Anderson"], ["ワルツィング・キャット", "L. Anderson"],
  ["シバの女王", "Laurent"], ["エーゲ海の真珠", "Paul Mauriat"], ["恋はみずいろ", "Paul Mauriat"],
  ["オリーブの首飾り", "Paul Mauriat"], ["渚のアデリーヌ", "Richard Clayderman"],
  ["愛のオルゴール", "Frank Mills"], ["虹の彼方に?", "Arlen"],
  ["ムーンライト・セレナーデ?", "Glenn Miller"], ["茶色の小瓶", "Glenn Miller"],
  ["アメリカン・パトロール", "Glenn Miller"],
  ["春の海", "宮城道雄"], ["六段の調", "八橋検校"], ["さくらさくら", "日本古謡"],
  ["越天楽", "雅楽"], ["君が代行進曲?", "雅楽?"], ["荒城の月", "滝廉太郎"],
  ["花", "滝廉太郎"], ["ふるさと", "岡野貞一"], ["朧月夜", "岡野貞一"],
  ["浜辺の歌", "成田為三"], ["この道", "山田耕筰"], ["赤とんぼ", "山田耕筰"],
  ["川の流れのように", "美空ひばり"], ["愛燦燦", "美空ひばり"], ["お祭りマンボ", "美空ひばり"],
  ["上を向いて歩こう", "坂本九"], ["見上げてごらん夜の星を", "坂本九"], ["明日があるさ", "坂本九"],
  ["また逢う日まで", "尾崎紀世彦"], ["世界は二人のために", "佐良直美"],
  ["てんとう虫のサンバ", "チェリッシュ"], ["瀬戸の花嫁", "小柳ルミ子"],
  ["3年目の浮気?", "ヒロシ&キーボー?"], ["関白宣言", "さだまさし"],
  ["秋桜", "さだまさし"], ["北の国から", "さだまさし"], ["奏（かなで）?", "さだ?"],
  ["未来へ?", "Kiroro?"], ["糸?", "中島みゆき?"],
];

// ================= シーン別 定番追加（実在曲・シーンタグ付き） =================
const SCENE_EXTRA = {
  entrance: [
    ["水平線", "back number"], ["Pretender?", "Official髭男dism?"], ["115万キロのフィルム", "Official髭男dism"],
    ["Magic?", "Mrs. GREEN APPLE?"], ["点描の唄", "Mrs. GREEN APPLE"], ["Stand by me, Stand by you.", "平井大"],
    ["ハッピーエンド?", "back number?"], ["アイラブユー", "back number"], ["Lovers?", "sumika?"],
    ["Perfect", "Ed Sheeran"], ["Thinking Out Loud", "Ed Sheeran"], ["All of Me", "John Legend"],
    ["A Thousand Years", "Christina Perri"], ["Speechless", "Dan + Shay"], ["Beautiful in White", "Shane Filan"],
    ["Can't Help Falling in Love", "Elvis Presley"], ["やさしいキスをして", "DREAMS COME TRUE"],
    ["幸せをありがとう", "ケツメイシ"], ["100万回の「I love you」", "Rake"], ["Wherever you are?", "ONE OK ROCK?"],
    ["君と羊と青", "RADWIMPS"], ["Hello,world!", "BUMP OF CHICKEN"], ["虹", "菅田将暉"],
    ["まちがいさがし", "菅田将暉"], ["さよならエレジー", "菅田将暉"], ["ラブレター", "YOASOBI"],
    ["群青?", "YOASOBI?"], ["ミライチズ", "梶原岳人?"], ["Universe", "Official髭男dism"],
  ],
  toast: [
    ["Paradise Has No Border", "東京スカパラダイスオーケストラ"], ["美しく燃える森", "東京スカパラダイスオーケストラ"],
    ["Can't Stop the Feeling!?", "Justin Timberlake?"], ["Cake by the Ocean", "DNCE"],
    ["Good Time", "Owl City & Carly Rae Jepsen"], ["On Our Way?", "The Royal Concept"],
    ["Shut Up and Dance", "WALK THE MOON"], ["Classic", "MKTO"], ["Talk Dirty?", "Jason Derulo?"],
    ["前向きスクリーム!", "関ジャニ∞"], ["ハピネス?", "AI?"], ["JOY?", "YUKI?"],
    ["Party Rock Anthem?", "LMFAO?"], ["Feel So Close?", "Calvin Harris?"],
    ["恋のブギウギナイト?", "サザン?"], ["匠(TAKUMI)?", "松谷卓?"],
  ],
  cake: [
    ["Sugar?", "Maroon 5?"], ["Sweets Parade?", "花たん?"], ["Chocolate?", "The 1975?"],
    ["ミルクコーヒー?", "須澤紀信?"], ["Honey", "L'Arc〜en〜Ciel"], ["はちみつ?", "スピッツ?"],
    ["CANDY POP?", "TWICE?"], ["Cheer up?", "TWICE?"], ["恋のマイアヒ?", "O-Zone?"],
  ],
  leave: [
    ["キセキ?", "GReeeeN?"], ["ありがとうの輪", "絢香"], ["ママへ?", "AI?"],
    ["秋桜?", "山口百恵?"], ["未来へ?", "Kiroro?"], ["おかあさん?", "?"],
  ],
  bouquet: [
    ["手紙 〜愛するあなたへ〜", "藤田麻衣子"], ["ありがとう ForzaStyle?", "?"],
    ["カンパニュラの恋?", "?"], ["最愛?", "KOH+?"], ["花束のかわりにメロディーを?", "清水翔太?"],
  ],
  farewell: [
    ["ありがとう?", "いきものがかり?"], ["Thank you, Love?", "西野カナ?"],
    ["虹?", "菅田将暉?"], ["カイト?", "嵐?"],
  ],
};

// ================= 展開ルール =================
// ウェディングBGM定番のアレンジ編成（婚礼BGM集・カバー音源として流通しているスタイル）
const POP_VARIANTS = [
  "ピアノver.", "オルゴールver.", "インストゥルメンタル", "アコースティックver.",
  "弦楽四重奏ver.", "ボサノバver.", "ジャズアレンジ", "ハープver.", "オーケストラver.",
];
const JAZZ_VARIANTS = ["ピアノトリオ", "ヴォーカルver.", "ビッグバンド", "ギターデュオ"];
const CLASSICAL_VARIANTS = ["ピアノ独奏", "弦楽四重奏", "オーケストラ", "パイプオルガン", "ハープ&フルート"];

const clean = (s) => s.replace(/\?+$/, "").trim();
const isJunk = (s) => /\?/.test(s) || !s;

const out = [];
const seen = new Set();
function push(scene, title, artist, variant) {
  title = clean(title); artist = clean(artist || "");
  if (!title || /\?/.test(title) || /\?/.test(artist)) return;
  const t = variant ? `${title}（${variant}）` : title;
  const key = `${t}${artist}`;
  if (seen.has(key)) return;
  seen.add(key);
  out.push({ s: scene, t, a: artist, ...(variant ? { v: 1 } : {}) });
}

// 1) J-POP / 洋楽（scene=party 汎用。歓談BGM・検索用）＋アレンジ展開
for (const [artist, songs] of [...Object.entries(JP), ...Object.entries(EN)]) {
  if (isJunk(artist)) continue;
  for (const song of songs) {
    if (isJunk(song)) continue;
    push("party", song, artist);
    for (const v of POP_VARIANTS) push("party", song, artist, v);
  }
}
// 2) 映画・ディズニー・ジブリ・アニメ
for (const [title, from] of THEMES) {
  if (isJunk(title)) continue;
  push("party", title, from);
  for (const v of POP_VARIANTS) push("party", title, from, v);
}
// 3) ジャズ
for (const title of JAZZ) {
  if (isJunk(title)) continue;
  push("party", title, "ジャズ・スタンダード");
  for (const v of JAZZ_VARIANTS) push("party", title, "ジャズ・スタンダード", v);
}
// 4) クラシック・讃美歌（chapel/ceremony向け）
for (const [title, composer] of CLASSICAL) {
  if (isJunk(title) || isJunk(composer)) continue;
  push("chapel", title, composer);
  for (const v of CLASSICAL_VARIANTS) push("chapel", title, composer, v);
}
// 5) シーン別 定番追加
for (const [scene, list] of Object.entries(SCENE_EXTRA)) {
  for (const [title, artist] of list) {
    if (isJunk(title) || isJunk(artist)) continue;
    push(scene, title, artist);
    for (const v of POP_VARIANTS.slice(0, 4)) push(scene, title, artist, v);
  }
}

const file = path.join(__dirname, "..", "src", "lib", "song-db-large.json");
fs.writeFileSync(file, JSON.stringify(out));
console.log(`✓ ${out.length}曲を生成しました → src/lib/song-db-large.json（${(fs.statSync(file).size / 1024 / 1024).toFixed(2)}MB）`);
